### ISSUE TITLE
Failed to build browser-package while running nextjs in dev mode

### ISSUE THREAD

**Issue by piyushchauhan2011** [moonrepo/examples#80]
After running the nextjs in dev mode, I tried updating the browser-package `index.ts` file where `add` function is present. I modified it to return `a + b + 1` but seems like we have to manually `build` the browser-package again to see the changes

`pnpm moon run nextjs-app:dev`

`pnpm moon run browser-package:build` in separate window

Is there a way to integrate this in same `dev` command ?

**Comment by milesj** [comment]
@piyushchauhan2011 This doesn't work because this is just how bundlers work. They don't rebuild if something in node_modules change, and that's how the package is currently being used in this example.

Using webpack/vite aliases is the proper way to handle this, it's not really a moon thing.

**Comment by piyushchauhan2011** [comment]
I see, all good 👍🏼
