### ISSUE TITLE
Problems when running dev task for nestjs-app

### ISSUE THREAD

**Issue by rlarac** [moonrepo/examples#84]
Hello,

I have been trying unsuccessfully to reference a project containing a **TypeScript** library** with another project that includes services implemented with **NestJS**. That’s why I decided to do a test and clone the examples repo, then try to replicate the configuration and understand why I have not been able to refer successfully. I also had no success trying the explicit configuration indicated in the [examples guide for NestJS](https://moonrepo.dev/docs/guides/examples/nest).

However, when trying to run the `dev` task of the `nestjs-app` project, I get a similar error, in this case:

```
Error: Cannot find module '/home/dev/experimental/moonrepo/.moon/cache/types/apps/nestjs-app/main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Function.Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
```

I understand that the configuration set for TypeScript in `toolchain.yml` (`routeOutDirToCache: true`) causes the `outDir` from the NestJS configuration (`nest-cli.json`) to be rewritten and point to Moon’s cache. However, there doesn’t seem to be any directory with the code transpiled to JavaScript.

It should be noted that the only thing I did after cloning the repo was to change the versions in `.moon/toolchain.json` for Node, as on my machine I have version 20.14.0 instead of version 20.13.1 and the version of PNPM has version 9.1.4 instead of 9.0.2. However, I installed versions 20.13.1 for Node and 9.0.2 for PNPM and the error persists.

The rest of the applications (Angular, Astro, NextJS, Nuxt, Remix, SvelteKit, and Vue+Vite), at least testing with the `dev` task work without any problem.

The versions of my toolchain:
- Node: 20.14.0 (I also tested with 20.13.1)
- PNPM: 9.1.4 (I also tested with 9.0.2)
- Moon: 1.25.0

The rest of the packages and their versions are the same as the `package.json` of the repository. I didn't modify any definition contained in the `.moon configuration` (neither `node-library.yml`, nor `node.yml` in the tasks directory, nor `toolchain.yml` nor `workspace.yml`.

Is there something misconfigured in the NestJS project? Thank you!

**Comment by milesj** [comment]
Thanks for reporting this, I'll take a look.

**Comment by milesj** [comment]
Fixed it by tweaking the tsconfig: https://github.com/moonrepo/examples/commit/ea1f2d9d45d1703b73873bd65dc945e3fec856ae
